// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FeedbackController from "./feedback_controller"
application.register("feedback", FeedbackController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import ReviewController from "./review_controller"
application.register("review", ReviewController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import UserPhotoPreviewController from "./user_photo_preview_controller"
application.register("user-photo-preview", UserPhotoPreviewController)
